### PR TITLE
Support RAILS_RELATIVE_URL_ROOT in routes for Rails apps running in a subdirectory

### PR DESCRIPTION
**Pull request by adamcrown**
I've added a scope for the RAILS_RELATIVE_URL_ROOT environment variable. This is needed in Rails 3 if an app is running in a subdirectory instead of it's own domain.

### CODE REVIEW

**Comment by neerajsingh0101** [comment]
Hi Adam,

Can you describe what you mean by "running app in a subdirectory"?

Thanks

**Comment by adamcrown** [comment]
If you run your app at `example.com`, everything works fine. But if you run your app at `example.com/rails_app` admin_data's routes still expect it to be run at `example.com/admin_data` instead of `example.com/rails_app/admin_data` so it doesn't work. This patch should allow either to work.

**Comment by neerajsingh0101** [comment]
makes sense. 

I will run a quick test and will merge it soon.

Thanks for quick feedback.

**Comment by neerajsingh0101** [comment]
Opening this ticket for documentation. The feature brought in this ticket should be documented.

**Pull request merged**
