### PR TITLE
Added support for more association types/info

### PR DESCRIPTION
**Pull request by chetan**
Hey,

I added support has_and_belongs_to_many in the various screens. You can now choose and update these objects using a multiple select box. I also added display of other relationship data. Let me know if you have any questions.

The first commit (82f402e4) was sort of a warmup; I originally intended to start by adding a datepicker widget to the edit screen but then moved on to the other stuff. I still intend to add that feature.

chetan

### CODE REVIEW

**Comment by neerajsingh0101** [comment]
I had a cursory look at changes. It looks pretty awesome. I will add some tests and will let you know.

Thanks for awesome work.

**Comment by neerajsingh0101** [comment]
I merged your changes in a separate branch. However something is not working right.

Go to https://github.com/neerajdotname/admin_data_test
Change the gemfile to point admin_data to 

```
gem 'admin_data', :git => 'git://github.com/neerajdotname/admin_data.git', :branch => 'habtm_support'
```

Then follow the process to run demo application.

When I click on a user show page, I get the list of clubs but when I click on clubs link then I get error.

I will look into it in a few days when I get time. In the meatime if you can take a look then that's great.

Thanks.

**Comment by chetan** [comment]
Ok, I'll take a look at it tonight. I made the changes against an app I was working on so I didn't try this demo. I'll check this out and let you know.

**Comment by neerajsingh0101** [comment]
thanks

**Comment by neerajsingh0101** [comment]
I found the problem and fixed it. https://github.com/neerajdotname/admin_data/commit/877e1b178e08993aca2638e0cf462d3fc614876f

I will write some tests as and when I get time and will push it when tests are done.

Sweet !!!

**Comment by chetan** [comment]
Looks good. I found another issue that I missed -- creating new records with habtm records fails. Going to fix that shortly.

**Comment by neerajsingh0101** [comment]
I have added you as a collaborator in admin_data so that we don't have to do this push/pull dance.

Just ensure that you are pushing changes to habtm_support branch of admin_data.

**Comment by chetan** [comment]
Just pushed my fix to the branch.

**Comment by neerajsingh0101** [comment]
looks good. I will try to write some long pending tests tomorrow.

My Instant message id is neerajdotname on all major IMs. Hit me up if you need something.

By the way just curios what kind of app you are working with and how much data you have?

**Pull request closed without merging**
